### ISSUE TITLE
update torch-family dependencies to still support cuda 11.6

### ISSUE THREAD

**Issue by deepchatterjeeligo** [ML4GW/ml4gw#102]
Many clusters still have not transitioned to newer cuda versions. However cuda 11.6 is incompatible with "torch > 2.0". Constrain the torch-family dependencies accordingly.

**Comment by deepchatterjeeligo** [comment]
This is relevant to `dev`

**Comment by wbenoit26** [comment]
The reason we upgraded `torch` was because of `torchaudio`. `torchaudio` 0.13 is incompatible with Python 3.11, but the following version of it requires `torch > 2.0`. So, it seems like our options are to either not support Python 3.11 or to not support `torch < 2.0`. I would think that it's fine to restrict our Python support, but happy to hear others' thoughts.

**Comment by deepchatterjeeligo** [comment]
I don't have any immediate need for python3.11. Current igwn conda distributions have support for all three 3.9, 3.10, and 3.11. In my opinion we still will be pretty up to date without 3.11, but if we need it, there has to be a way worked out for cuda 11.6 and 11.7 since they are not completely phased out.

**Comment by wbenoit26** [comment]
Yeah, I'll make a PR for this, and we can re-visit the issue if we ever run into a problem with downgrading python.

**Comment by alecgunny** [comment]
FWIW, in poetry you can make your dependencies [specific to your target Python versions](https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies). So you could e.g. agree to use torch < 2.0 if the user is willing to use python <3.10, otherwise they have to use torch 2.x. But this obviously adds a layer of complication, just figured I'd mention it.

**Comment by wbenoit26** [comment]
Oh cool, I like that, thanks for pointing it out. @deepchatterjeeligo I'll update my PR to have that in there

**Comment by deepchatterjeeligo** [comment]
solved by #103
