### ISSUE TITLE
bump `bilby` dep to `2.0.0`

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/ml4gw#53]
Bilby is onto version 2.0.x , which `ml4gw` does not support, although I don't think there are any major changes that will effect `ml4gw` apis.

**Comment by alecgunny** [comment]
Agreed, and this will be helpful for conda environments where all the GW stuff is managed by conda. We should still hang on to this as a dev dependency though to use bilby as a source of truth during testing

**Comment by alecgunny** [comment]
You could also really make the same argument about `gwpy`, which only gets used for normalizing backgrounds. We could start using our Welch code to convert from time to PSD space ourselves, and just enforce that users have already sorted out all the sample rate stuff on their own. We could even include a separate `.fit_psd` method that takes pre-computed PSDs as input, rather than having `.fit` be hyper flexible
